name = "ZGNAV"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liaN4kkyObZcHDht"
GITHUB_OWNER = "csbde"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.zoogooo.com/api/auth"
NEXT_PUBLIC_API_URL="https://nav.zoogooo.com"

